name 'build-server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures build-server'
long_description 'Installs/Configures build-server'
version '0.1.0'

depends 'jenkins', '~> 2.4.1'
depends 'java',  '~> 1.39.0'
